name: Build and publish xk6-image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Git tag to build release from
        required: true
        
jobs:
  build:
    name: Build xk6-kafka
    runs-on: ubuntu-latest
    permissions:
      checks: write
      packages: write
      repository-projects: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2     

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image 
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ghcr.io/nsl-test/xk6
          tags: ${{ github.event.inputs.tag }}
          archs: amd64, arm64
          dockerfiles: |
            ./Dockerfile    

      - name: Docker build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          image: ghcr.io/nsl-test/xk6
          tags: ${{ github.event.inputs.tag }}
